# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build and Push an image
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/azure-vote/Dockerfile'
        containerRegistry: acrunyleya-rg
        repository: app
        tags: |
          $(tag)
          latest
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)/unyleya'
        ArtifactName: 'unyleya'
        publishLocation: 'Container'